// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: table.proto

package eg.edu.alexu.csd.oop.jdbc.table;

public final class PBGeneratedTable {
	/**
	 * Protobuf type {@code protobuf.Table}
	 */
	public static final class Table extends
			com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:protobuf.Table)
			TableOrBuilder {
		/**
		 * Protobuf type {@code protobuf.Table}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
				// @@protoc_insertion_point(builder_implements:protobuf.Table)
				eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.TableOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_descriptor;
			}

			private int bitField0_;

			private java.lang.Object name_ = "";

			private java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> columns_ = java.util.Collections
					.emptyList();

			private com.google.protobuf.RepeatedFieldBuilderV3<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder> columnsBuilder_;

			// Construct using
			// eg.edu.alexu.csd.oop.jdbc.protobuf.PBGeneratedTable.Table.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder addAllColumns(
					final java.lang.Iterable<? extends eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> values) {
				if (columnsBuilder_ == null) {
					ensureColumnsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(
							values, columns_);
					onChanged();
				} else {
					columnsBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder addColumns(
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column value) {
				if (columnsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureColumnsIsMutable();
					columns_.add(value);
					onChanged();
				} else {
					columnsBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder addColumns(
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder builderForValue) {
				if (columnsBuilder_ == null) {
					ensureColumnsIsMutable();
					columns_.add(builderForValue.build());
					onChanged();
				} else {
					columnsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder addColumns(
					final int index,
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column value) {
				if (columnsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureColumnsIsMutable();
					columns_.add(index, value);
					onChanged();
				} else {
					columnsBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder addColumns(
					final int index,
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder builderForValue) {
				if (columnsBuilder_ == null) {
					ensureColumnsIsMutable();
					columns_.add(index, builderForValue.build());
					onChanged();
				} else {
					columnsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder addColumnsBuilder() {
				return getColumnsFieldBuilder()
						.addBuilder(
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column
										.getDefaultInstance());
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder addColumnsBuilder(
					final int index) {
				return getColumnsFieldBuilder()
						.addBuilder(
								index,
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column
										.getDefaultInstance());
			}

			@Override
			public Builder addRepeatedField(
					final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table build() {
				eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@SuppressWarnings("unused")
			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table buildPartial() {
				eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table result = new eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				result.name_ = name_;
				if (columnsBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						columns_ = java.util.Collections
								.unmodifiableList(columns_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.columns_ = columns_;
				} else {
					result.columns_ = columnsBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clear() {
				super.clear();
				name_ = "";

				if (columnsBuilder_ == null) {
					columns_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					columnsBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder clearColumns() {
				if (columnsBuilder_ == null) {
					columns_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					columnsBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clearField(
					final com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			@Override
			public Builder clearOneof(
					final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			private void ensureColumnsIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					columns_ = new java.util.ArrayList<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column>(
							columns_);
					bitField0_ |= 0x00000002;
				}
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getColumns(
					final int index) {
				if (columnsBuilder_ == null) {
					return columns_.get(index);
				} else {
					return columnsBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder getColumnsBuilder(
					final int index) {
				return getColumnsFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder> getColumnsBuilderList() {
				return getColumnsFieldBuilder().getBuilderList();
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			@Override
			public int getColumnsCount() {
				if (columnsBuilder_ == null) {
					return columns_.size();
				} else {
					return columnsBuilder_.getCount();
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder> getColumnsFieldBuilder() {
				if (columnsBuilder_ == null) {
					columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder, eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder>(
							columns_,
							((bitField0_ & 0x00000002) == 0x00000002),
							getParentForChildren(), isClean());
					columns_ = null;
				}
				return columnsBuilder_;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			@Override
			public java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> getColumnsList() {
				if (columnsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(columns_);
				} else {
					return columnsBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder getColumnsOrBuilder(
					final int index) {
				if (columnsBuilder_ == null) {
					return columns_.get(index);
				} else {
					return columnsBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			@Override
			public java.util.List<? extends eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder> getColumnsOrBuilderList() {
				if (columnsBuilder_ != null) {
					return columnsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(columns_);
				}
			}

			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table getDefaultInstanceForType() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table
						.getDefaultInstance();
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_descriptor;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.class,
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Builder.class);
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getColumnsFieldBuilder();
				}
			}

			@Override
			public Builder mergeFrom(
					final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table) e
							.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.Message other) {
				if (other instanceof eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table) {
					return mergeFrom((eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table other) {
				if (other == eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table
						.getDefaultInstance()) {
					return this;
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (columnsBuilder_ == null) {
					if (!other.columns_.isEmpty()) {
						if (columns_.isEmpty()) {
							columns_ = other.columns_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureColumnsIsMutable();
							columns_.addAll(other.columns_);
						}
						onChanged();
					}
				} else {
					if (!other.columns_.isEmpty()) {
						if (columnsBuilder_.isEmpty()) {
							columnsBuilder_.dispose();
							columnsBuilder_ = null;
							columns_ = other.columns_;
							bitField0_ = (bitField0_ & ~0x00000002);
							columnsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getColumnsFieldBuilder()
									: null;
						} else {
							columnsBuilder_.addAllMessages(other.columns_);
						}
					}
				}
				onChanged();
				return this;
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder removeColumns(final int index) {
				if (columnsBuilder_ == null) {
					ensureColumnsIsMutable();
					columns_.remove(index);
					onChanged();
				} else {
					columnsBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder setColumns(
					final int index,
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column value) {
				if (columnsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureColumnsIsMutable();
					columns_.set(index, value);
					onChanged();
				} else {
					columnsBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .protobuf.Table.Column columns = 2;</code>
			 */
			public Builder setColumns(
					final int index,
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder builderForValue) {
				if (columnsBuilder_ == null) {
					ensureColumnsIsMutable();
					columns_.set(index, builderForValue.build());
					onChanged();
				} else {
					columnsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			@Override
			public Builder setField(
					final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.setField(field, value);
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setNameBytes(
					final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			@Override
			public Builder setRepeatedField(
					final com.google.protobuf.Descriptors.FieldDescriptor field,
					final int index, final Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:protobuf.Table)
		}

		/**
		 * Protobuf type {@code protobuf.Table.Column}
		 */
		public static final class Column extends
				com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:protobuf.Table.Column)
				ColumnOrBuilder {
			/**
			 * Protobuf type {@code protobuf.Table.Column}
			 */
			public static final class Builder extends
					com.google.protobuf.GeneratedMessageV3.Builder<Builder>
					implements
					// @@protoc_insertion_point(builder_implements:protobuf.Table.Column)
					eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_Column_descriptor;
				}

				private int bitField0_;

				private java.lang.Object name_ = "";

				private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;

				// Construct using
				// eg.edu.alexu.csd.oop.jdbc.protobuf.PBGeneratedTable.Table.Column.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(
						final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				public Builder addAllValue(
						final java.lang.Iterable<java.lang.String> values) {
					ensureValueIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(
							values, value_);
					onChanged();
					return this;
				}

				@Override
				public Builder addRepeatedField(
						final com.google.protobuf.Descriptors.FieldDescriptor field,
						final Object value) {
					return super.addRepeatedField(field, value);
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				public Builder addValue(final java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValueIsMutable();
					value_.add(value);
					onChanged();
					return this;
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				public Builder addValueBytes(
						final com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);
					ensureValueIsMutable();
					value_.add(value);
					onChanged();
					return this;
				}

				@Override
				public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column build() {
					eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				@SuppressWarnings("unused")
				@Override
				public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column buildPartial() {
					eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column result = new eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column(
							this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					result.name_ = name_;
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						value_ = value_.getUnmodifiableView();
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.value_ = value_;
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				@Override
				public Builder clear() {
					super.clear();
					name_ = "";

					value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
					bitField0_ = (bitField0_ & ~0x00000002);
					return this;
				}

				@Override
				public Builder clearField(
						final com.google.protobuf.Descriptors.FieldDescriptor field) {
					return super.clearField(field);
				}

				/**
				 * <code>optional string name = 1;</code>
				 */
				public Builder clearName() {

					name_ = getDefaultInstance().getName();
					onChanged();
					return this;
				}

				@Override
				public Builder clearOneof(
						final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return super.clearOneof(oneof);
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				public Builder clearValue() {
					value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
					return this;
				}

				@Override
				public Builder clone() {
					return super.clone();
				}

				private void ensureValueIsMutable() {
					if (!((bitField0_ & 0x00000002) == 0x00000002)) {
						value_ = new com.google.protobuf.LazyStringArrayList(
								value_);
						bitField0_ |= 0x00000002;
					}
				}

				@Override
				public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getDefaultInstanceForType() {
					return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column
							.getDefaultInstance();
				}

				@Override
				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_Column_descriptor;
				}

				/**
				 * <code>optional string name = 1;</code>
				 */
				@Override
				public java.lang.String getName() {
					java.lang.Object ref = name_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						name_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>optional string name = 1;</code>
				 */
				@Override
				public com.google.protobuf.ByteString getNameBytes() {
					java.lang.Object ref = name_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString
								.copyFromUtf8((java.lang.String) ref);
						name_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				@Override
				public java.lang.String getValue(final int index) {
					return value_.get(index);
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				@Override
				public com.google.protobuf.ByteString getValueBytes(
						final int index) {
					return value_.getByteString(index);
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				@Override
				public int getValueCount() {
					return value_.size();
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				@Override
				public com.google.protobuf.ProtocolStringList getValueList() {
					return value_.getUnmodifiableView();
				}

				@Override
				protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
					return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_Column_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.class,
									eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder.class);
				}

				@Override
				public final boolean isInitialized() {
					return true;
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					}
				}

				@Override
				public Builder mergeFrom(
						final com.google.protobuf.CodedInputStream input,
						final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
					eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input,
								extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column) e
								.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				@Override
				public Builder mergeFrom(final com.google.protobuf.Message other) {
					if (other instanceof eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column) {
						return mergeFrom((eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(
						final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column other) {
					if (other == eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column
							.getDefaultInstance()) {
						return this;
					}
					if (!other.getName().isEmpty()) {
						name_ = other.name_;
						onChanged();
					}
					if (!other.value_.isEmpty()) {
						if (value_.isEmpty()) {
							value_ = other.value_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureValueIsMutable();
							value_.addAll(other.value_);
						}
						onChanged();
					}
					onChanged();
					return this;
				}

				@Override
				public final Builder mergeUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return this;
				}

				@Override
				public Builder setField(
						final com.google.protobuf.Descriptors.FieldDescriptor field,
						final Object value) {
					return super.setField(field, value);
				}

				/**
				 * <code>optional string name = 1;</code>
				 */
				public Builder setName(final java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					name_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>optional string name = 1;</code>
				 */
				public Builder setNameBytes(
						final com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					name_ = value;
					onChanged();
					return this;
				}

				@Override
				public Builder setRepeatedField(
						final com.google.protobuf.Descriptors.FieldDescriptor field,
						final int index, final Object value) {
					return super.setRepeatedField(field, index, value);
				}

				@Override
				public final Builder setUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return this;
				}

				/**
				 * <code>repeated string value = 2;</code>
				 */
				public Builder setValue(final int index,
						final java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValueIsMutable();
					value_.set(index, value);
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:protobuf.Table.Column)
			}

			public static final int NAME_FIELD_NUMBER = 1;

			public static final int VALUE_FIELD_NUMBER = 2;

			private static final long serialVersionUID = 0L;

			// @@protoc_insertion_point(class_scope:protobuf.Table.Column)
			private static final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column DEFAULT_INSTANCE;

			static {
				DEFAULT_INSTANCE = new eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column();
			}

			private static final com.google.protobuf.Parser<Column> PARSER = new com.google.protobuf.AbstractParser<Column>() {
				@Override
				public Column parsePartialFrom(
						final com.google.protobuf.CodedInputStream input,
						final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new Column(input, extensionRegistry);
				}
			};

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_Column_descriptor;
			}

			public static Builder newBuilder() {
				return DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(
					final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column prototype) {
				return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseDelimitedFrom(
					final java.io.InputStream input) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseDelimitedFrom(
					final java.io.InputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input,
								extensionRegistry);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final byte[] data,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final com.google.protobuf.ByteString data,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final com.google.protobuf.CodedInputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final java.io.InputStream input) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column parseFrom(
					final java.io.InputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static com.google.protobuf.Parser<Column> parser() {
				return PARSER;
			}

			@SuppressWarnings("unused")
			private int bitField0_;

			private volatile java.lang.Object name_;

			private com.google.protobuf.LazyStringList value_;

			private byte memoizedIsInitialized = -1;

			private Column() {
				name_ = "";
				value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			}

			private Column(
					final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				int mutable_bitField0_ = 0;
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!input.skipField(tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							java.lang.String s = input.readStringRequireUtf8();

							name_ = s;
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();
							if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
								value_ = new com.google.protobuf.LazyStringArrayList();
								mutable_bitField0_ |= 0x00000002;
							}
							value_.add(s);
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(
							e).setUnfinishedMessage(this);
				} finally {
					if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
						value_ = value_.getUnmodifiableView();
					}
					makeExtensionsImmutable();
				}
			}

			// Use Column.newBuilder() to construct.
			private Column(
					final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			@java.lang.Override
			public boolean equals(final java.lang.Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column)) {
					return super.equals(obj);
				}
				eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column other = (eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column) obj;

				boolean result = true;
				result = result && getName().equals(other.getName());
				result = result && getValueList().equals(other.getValueList());
				return result;
			}

			@Override
			public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getDefaultInstanceForType() {
				return DEFAULT_INSTANCE;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			@java.lang.Override
			public com.google.protobuf.Parser<Column> getParserForType() {
				return PARSER;
			}

			@Override
			public int getSerializedSize() {
				int size = memoizedSize;
				if (size != -1) {
					return size;
				}

				size = 0;
				if (!getNameBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3
							.computeStringSize(1, name_);
				}
				{
					int dataSize = 0;
					for (int i = 0; i < value_.size(); i++) {
						dataSize += computeStringSizeNoTag(value_.getRaw(i));
					}
					size += dataSize;
					size += 1 * getValueList().size();
				}
				memoizedSize = size;
				return size;
			}

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			/**
			 * <code>repeated string value = 2;</code>
			 */
			@Override
			public java.lang.String getValue(final int index) {
				return value_.get(index);
			}

			/**
			 * <code>repeated string value = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getValueBytes(final int index) {
				return value_.getByteString(index);
			}

			/**
			 * <code>repeated string value = 2;</code>
			 */
			@Override
			public int getValueCount() {
				return value_.size();
			}

			/**
			 * <code>repeated string value = 2;</code>
			 */
			@Override
			public com.google.protobuf.ProtocolStringList getValueList() {
				return value_;
			}

			@SuppressWarnings("unchecked")
			@java.lang.Override
			public int hashCode() {
				if (memoizedHashCode != 0) {
					return memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + getDescriptorForType().hashCode();
				hash = (37 * hash) + NAME_FIELD_NUMBER;
				hash = (53 * hash) + getName().hashCode();
				if (getValueCount() > 0) {
					hash = (37 * hash) + VALUE_FIELD_NUMBER;
					hash = (53 * hash) + getValueList().hashCode();
				}
				hash = (29 * hash) + unknownFields.hashCode();
				memoizedHashCode = hash;
				return hash;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_Column_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.class,
								eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column.Builder.class);
			}

			@Override
			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1) {
					return true;
				}
				if (isInitialized == 0) {
					return false;
				}

				memoizedIsInitialized = 1;
				return true;
			}

			@Override
			public Builder newBuilderForType() {
				return newBuilder();
			}

			@java.lang.Override
			protected Builder newBuilderForType(
					final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			@Override
			public Builder toBuilder() {
				return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
						.mergeFrom(this);
			}

			@Override
			public void writeTo(
					final com.google.protobuf.CodedOutputStream output)
					throws java.io.IOException {
				if (!getNameBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output,
							1, name_);
				}
				for (int i = 0; i < value_.size(); i++) {
					com.google.protobuf.GeneratedMessageV3.writeString(output,
							2, value_.getRaw(i));
				}
			}

		}

		public interface ColumnOrBuilder extends
		// @@protoc_insertion_point(interface_extends:protobuf.Table.Column)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>optional string name = 1;</code>
			 */
			java.lang.String getName();

			/**
			 * <code>optional string name = 1;</code>
			 */
			com.google.protobuf.ByteString getNameBytes();

			/**
			 * <code>repeated string value = 2;</code>
			 */
			java.lang.String getValue(int index);

			/**
			 * <code>repeated string value = 2;</code>
			 */
			com.google.protobuf.ByteString getValueBytes(int index);

			/**
			 * <code>repeated string value = 2;</code>
			 */
			int getValueCount();

			/**
			 * <code>repeated string value = 2;</code>
			 */
			java.util.List<java.lang.String> getValueList();
		}

		public static final int NAME_FIELD_NUMBER = 1;

		public static final int COLUMNS_FIELD_NUMBER = 2;

		private static final long serialVersionUID = 0L;

		// @@protoc_insertion_point(class_scope:protobuf.Table)
		private static final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table();
		}

		private static final com.google.protobuf.Parser<Table> PARSER = new com.google.protobuf.AbstractParser<Table>() {
			@Override
			public Table parsePartialFrom(
					final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Table(input, extensionRegistry);
			}
		};

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_descriptor;
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(
				final eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseDelimitedFrom(
				final java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseDelimitedFrom(
				final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input,
							extensionRegistry);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final byte[] data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final com.google.protobuf.ByteString data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input, extensionRegistry);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input);
		}

		public static eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table parseFrom(
				final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input, extensionRegistry);
		}

		public static com.google.protobuf.Parser<Table> parser() {
			return PARSER;
		}

		@SuppressWarnings("unused")
		private int bitField0_;

		private volatile java.lang.Object name_;

		private java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> columns_;

		private byte memoizedIsInitialized = -1;

		private Table() {
			name_ = "";
			columns_ = java.util.Collections.emptyList();
		}

		private Table(
				final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 18: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							columns_ = new java.util.ArrayList<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column>();
							mutable_bitField0_ |= 0x00000002;
						}
						columns_.add(input
								.readMessage(
										eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column
												.parser(), extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					columns_ = java.util.Collections.unmodifiableList(columns_);
				}
				makeExtensionsImmutable();
			}
		}

		// Use Table.newBuilder() to construct.
		private Table(
				final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table)) {
				return super.equals(obj);
			}
			eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table other = (eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table) obj;

			boolean result = true;
			result = result && getName().equals(other.getName());
			result = result && getColumnsList().equals(other.getColumnsList());
			return result;
		}

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		@Override
		public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getColumns(
				final int index) {
			return columns_.get(index);
		}

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		@Override
		public int getColumnsCount() {
			return columns_.size();
		}

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		@Override
		public java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> getColumnsList() {
			return columns_;
		}

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		@Override
		public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder getColumnsOrBuilder(
				final int index) {
			return columns_.get(index);
		}

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		@Override
		public java.util.List<? extends eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder> getColumnsOrBuilderList() {
			return columns_;
		}

		@Override
		public eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Table> getParserForType() {
			return PARSER;
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3
						.computeStringSize(1, name_);
			}
			for (int i = 0; i < columns_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(2, columns_.get(i));
			}
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		@SuppressWarnings("unchecked")
		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			if (getColumnsCount() > 0) {
				hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
				hash = (53 * hash) + getColumnsList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.internal_static_protobuf_Table_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.class,
							eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Builder.class);
		}

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
					.mergeFrom(this);
		}

		@Override
		public void writeTo(final com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1,
						name_);
			}
			for (int i = 0; i < columns_.size(); i++) {
				output.writeMessage(2, columns_.get(i));
			}
		}

	}

	public interface TableOrBuilder extends
	// @@protoc_insertion_point(interface_extends:protobuf.Table)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column getColumns(
				int index);

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		int getColumnsCount();

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		java.util.List<eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.Column> getColumnsList();

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder getColumnsOrBuilder(
				int index);

		/**
		 * <code>repeated .protobuf.Table.Column columns = 2;</code>
		 */
		java.util.List<? extends eg.edu.alexu.csd.oop.jdbc.table.PBGeneratedTable.Table.ColumnOrBuilder> getColumnsOrBuilderList();

		/**
		 * <code>optional string name = 1;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>optional string name = 1;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_protobuf_Table_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_protobuf_Table_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_protobuf_Table_Column_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_protobuf_Table_Column_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\013table.proto\022\010protobuf\"e\n\005Table\022\014\n\004name"
				+ "\030\001 \001(\t\022\'\n\007columns\030\002 \003(\0132\026.protobuf.Table"
				+ ".Column\032%\n\006Column\022\014\n\004name\030\001 \001(\t\022\r\n\005value"
				+ "\030\002 \003(\tB\034\n\010protobufB\020PBGeneratedTableb\006pr"
				+ "oto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					final com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
		internal_static_protobuf_Table_descriptor = getDescriptor()
				.getMessageTypes().get(0);
		internal_static_protobuf_Table_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_protobuf_Table_descriptor,
				new java.lang.String[] { "Name", "Columns", });
		internal_static_protobuf_Table_Column_descriptor = internal_static_protobuf_Table_descriptor
				.getNestedTypes().get(0);
		internal_static_protobuf_Table_Column_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_protobuf_Table_Column_descriptor,
				new java.lang.String[] { "Name", "Value", });
	}

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	public static void registerAllExtensions(
			final com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public static void registerAllExtensions(
			final com.google.protobuf.ExtensionRegistryLite registry) {
	}

	private PBGeneratedTable() {
	}

	// @@protoc_insertion_point(outer_class_scope)
}